dry-dock/u16all

Dockerfile, build.sh, install.sh, my.cnf, neo4j-server.properties, pg_hba.cnf, version/couchdb_1_6.sh, version/elasticsearch_2_4.sh, version/memcached_1_4.sh, version/mongodb_3_2.sh, version/mysql_5_7.sh, version/neo4j_3_0.sh, version/postgres_9_4.sh, version/rabbitmq_3_6.sh, version/redis_3_0.sh, version/rethinkdb_2_3.sh, version/riak_latest.sh, version/selenium_2_53.sh, version/sqlite_3.sh
https://github.com/dry-dock/u16all/issues/1
- Adds Dockerfile and install scripts
- Tests are not included, as they don't work yet for u16
Tested  by building the image, running the resulting image, and checking that each of the services is present
=> Adds dockerfile and service install scripts

Dockerfile, README.md, install.sh, test/_cassandra.sh, test/_couchdb.sh, test/_elasticsearch.sh, test/_memcached.sh, test/_mongo.sh, test/_mysql.sh, test/_neo4j.sh, test/_postgres.sh, test/_rabbitmq.sh, test/_redis.sh, test/_rethinkdb.sh, test/_riak.sh, test/_selenium.sh, test/function_start_generic.sh, version/cassandra_3_6.sh, version/couchdb_1_6.sh, version/elasticsearch_2_4.sh, version/neo4j_3_0.sh, version/postgres_9_6.sh, version/redis_3_0.sh, version/rethinkdb_2_3.sh, version/riak_latest.sh
https://github.com/dry-dock/u16all/issues/1
- Changes {{TAG} to {{%TAG%}} in Dockerfile
- UPdates postgres to 9.6
- Adds tests
Tests worked locally once netcat was installed (which is being added to the base image)
=> Add tests, update postgres to 9.6, fix TAG in Dockerfile

README.md, version/riak_2_0.sh
https://github.com/dry-dock/u16all/issues/1
- Change riak version in README and filename from "latest" to 2.0.7
=> Change riak version in README from 'latest' to 2.0.7

version/postgres_9_6.sh
=> Add postgis

version/memcached_1_4.sh
=> Add libsasl2-dev

README.md, test/_selenium.sh, version/selenium.sh
https://github.com/dry-dock/u16all/issues/13
=> update selenium version to 3.4.0

services/selenium.sh
https://github.com/dry-dock/u16all/issues/13
=> adds selenium to startup services

services/postgres.sh, services/postgres_env.sh
fixes https://github.com/dry-dock/u16all/issues/16
=> DEV MVP 5 Create and  source the env files necessary to boot postgres.

services/cassandra.sh, services/cassandra_env.sh, services/couchdb.sh, services/couchdb_env.sh, services/elasticsearch.sh, services/elasticsearch_env.sh, services/memcached.sh, services/memcached_env.sh, services/mongodb.sh, services/mongodb_env.sh, services/mysql.sh, services/mysql_env.sh, services/neo4j.sh, services/neo4j_env.sh, services/rabbitmq.sh, services/rabbitmq_env.sh, services/redis.sh, services/redis_env.sh, services/rethinkdb.sh, services/rethinkdb_env.sh, services/selenium.sh, services/selenium_env.sh
fixes https://github.com/dry-dock/u16all/issues/16
=> create and source env files for all the services

version/cassandra.sh, version/cassandra_3_11.sh
fixes https://github.com/dry-dock/u16all/issues/19
verified on my local system by starting , stopping cassandra  and verified the version .
=> update cassandra from 3.9 to 3.11

version/elasticsearch_5_5_0.sh
fixes https://github.com/dry-dock/u16all/issues/30
verified on my local system by starting and stopping elasticsearch and verified the version
=> update elasticsearch 5.1.2 to 5.5.0

version/mongodb_3_4_6.sh
fixes https://github.com/dry-dock/u16all/issues/28
verified on my local system by starting and stopping mongodb and verified the version .
=> update mongodb from 3.4 to 3.4.6

version/redis_3_2_9.sh
fixes https://github.com/dry-dock/u16all/issues/23
verified on local system by starting ,stopping and verified the version of redis
=> update redis from 3.2 to 3.2.9

services/couchdb_env.sh, services/rabbitmq.sh, test/_rabbitmq.sh
from https://github.com/dry-dock/u16all/issues/24
=> shutdown rabbitmq gracefully

version/sqlite_3.sh, version/sqlite_3_19_3.sh
fixes https://github.com/dry-dock/u16all/issues/20
verified on local system by starting ,stopping and verified the version of sqlite
=> update sqlite from 3.0 to 3.19.3

version/mysql_5_7_18.sh
https://github.com/dry-dock/u16all/issues/51
=> add soft link to correct mysql socket pointer

services/mysql.sh, version/mysql_5_7_18.sh
https://github.com/dry-dock/u16all/issues/51
=> create symlink for tmp/mysql.sock

services/neo4j.sh, services/neo4j_env.sh, test/_neo4j.sh, version/neo4j_3_2_6.sh
https://github.com/dry-dock/u16all/issues/57
=> installs neo4j from tarball

version/redis_4_0_2.sh
=> update redis server version

services/selenium_env.sh
https://github.com/dry-dock/u16all/issues/78
=> update selenium start script

services/postgres_env.sh, version/redis_4_0_7.sh, version/sqlite_3_22.0.sh
https://github.com/dry-dock/u16all/issues/82
update redis-server minor version to fix failing build
and sets postgres env var
=> set postgres env var for shippable service 

services/mysql.sh, services/postgres.sh, version/redis_4_0.sh
https://github.com/dry-dock/u16all/issues/85
https://github.com/dry-dock/u16all/issues/84
able to build u16all locally
=> u16all - mysql and postgres should fail build if service start fails

version/selenium_3_8_1.sh
https://github.com/dry-dock/u16all/issues/87
built image locally and checked that latest chrome driver version 2.35 is installed.
=> install latest chrome driver version along with chrome

test/_elasticsearch.sh, test/_postgres.sh, test/_selenium.sh
=> update start service test scripts in u16all for elasticsearch, postgres and selenium

README.md
https://github.com/dry-dock/u16all/issues/89
=> update service versions in README.md

version/elasticsearch_6_2_3.sh, version/memcached_1_5_7.sh
https://github.com/dry-dock/u16all/issues/93
=> updated the latest versions

version/postgres_10.sh
https://github.com/Shippable/pm/issues/10522
=> Update and rename postgres_10_3.sh to postgres_10.sh

version/neo4j_3_3_4.sh
https://github.com/dry-dock/u16all/issues/92
=> Neo4j updated version

version/rabbitmq_3_7_4.sh
https://github.com/dry-dock/u16all/issues/92
=> RABBITMQ update version

version/elasticsearch_6_2_4.sh
https://github.com/dry-dock/u16all/issues/106
=> Update and rename elasticsearch_6_2_3.sh to elasticsearch_6_2_4.sh

version/postgres_10.3.sh
https://github.com/dry-dock/u16all/issues/114
=> Update and rename postgres_10.sh to postgres_10.3.sh

README.md, version/selenium_3_11_0.sh
https://github.com/dry-dock/u16all/issues/120
=> selenium and readme file update for u16all images 

install.sh, version/redis_4_0_9.sh
https://github.com/Shippable/pm/issues/11009
https://github.com/Shippable/heap/issues/2388
=> updating install.sh file 

README.md, version/elasticsearch_6_4_0.sh, version/memcached_1_5_10.sh, version/mongodb_4_0_2.sh, version/neo4j_3_3_7.sh
https://github.com/dry-dock/u16all/issues/167
https://github.com/dry-dock/u16all/issues/168
https://github.com/dry-dock/u16all/issues/169
https://github.com/dry-dock/u16all/issues/170
=> latest updated version for drydock u16all image 

README.md, install.sh
https://github.com/Shippable/pm/issues/11547
=> updating Dockerhub/drydock link git repo  u16all 

README.md, version/redis_5_0_2.sh
https://github.com/Shippable/pm/issues/11520
=> update latest redis version for u16all image
